sonar.projectKey=portfolio-api
sonar.projectName=portfolio-api
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.exclusions=node_modules/**
sonar.tests=src/tests
sonar.test.inclusions=**/*.test.js
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.scanner.skipJreProvisioning=true

sonar.javascript.lcov.reportPaths=coverage/lcov.info
