sonar.projectKey=portfolio-react
sonar.projectName=portfolio-react
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.exclusions=node_modules/**
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.scanner.skipJreProvisioning=true

sonar.javascript.lcov.reportPaths=coverage/lcov.info
